class XorgFonts < Formula
  desc "X.Org Fonts"
  homepage "http://www.x.org/"
  ### http://www.linuxfromscratch.org/blfs/view/svn/x/x7lib.html
  url "https://gist.githubusercontent.com/maxim-belkin/6fd6422cbe4da6ea0555d7a8d9911bc2/raw/c38d109967382d35f9f8a89542c18abbfb27cf88/README.md"
  version  "20160522"
  sha256   "3baf64afb29129ea9f74d5ae5a223b072d0911d96283f834e37d8f65d751c5d7"
  # tag "linuxbrew"

  bottle :unneeded

  depends_on "font-util"
  depends_on "encodings"
  depends_on "font-adobe-100dpi"
  depends_on "font-adobe-75dpi"
  depends_on "font-adobe-utopia-100dpi"
  depends_on "font-adobe-utopia-75dpi"
  depends_on "font-adobe-utopia-type1"
  depends_on "font-alias"
  depends_on "font-arabic-misc"
  depends_on "font-bh-100dpi"
  depends_on "font-bh-75dpi"
  depends_on "font-bh-lucidatypewriter-100dpi"
  depends_on "font-bh-lucidatypewriter-75dpi"
  depends_on "font-bh-ttf"
  depends_on "font-bh-type1"
  depends_on "font-bitstream-100dpi"
  depends_on "font-bitstream-75dpi"
  depends_on "font-bitstream-type1"
  depends_on "font-cronyx-cyrillic"
  depends_on "font-cursor-misc"
  depends_on "font-daewoo-misc"
  depends_on "font-dec-misc"
  depends_on "font-ibm-type1"
  depends_on "font-isas-misc"
  depends_on "font-jis-misc"
  depends_on "font-micro-misc"
  depends_on "font-misc-cyrillic"
  depends_on "font-misc-ethiopic"
  depends_on "font-misc-meltho"
  depends_on "font-misc-misc"
  depends_on "font-mutt-misc"
  depends_on "font-schumacher-misc"
  depends_on "font-screen-cyrillic"
  depends_on "font-sony-misc"
  depends_on "font-sun-misc"
  depends_on "font-winitzki-cyrillic"
  depends_on "font-xfree86-type1"

  def install
    ohai "Xorg Fonts have been installed!"
    prefix.install "README.md" => "xorg-fonts.md"
  end
end
